FROM ubuntu:24.04

ARG MAKEARGS
RUN echo "MAKEARGS: ${MAKEARGS}"

ENV DEBIAN_FRONTEND=noninteractive

# Build and test dependencies
RUN apt-get update \
 && apt-get install -y --no-install-recommends \
    gcc g++ make patch unzip perl git ca-certificates \
    automake autoconf libtool cmake pkg-config nasm yasm xz-utils tclsh \
    zlib1g-dev liblzma-dev golang-go \
    libasan8 \
 && rm -rf /var/lib/apt/lists/*

# Build and install SRS.
COPY . /srs
WORKDIR /srs/trunk

# Note that we must enable the gcc7 or link failed.
# Please note that we must disable the ffmpeg-opus, as it negatively impacts performance. We may consider
# enabling it in the future when support for multi-threading transcoding is available.
# Enable sanitizer explicitly for CI/CD testing to catch memory issues.
RUN ./configure --srt=on --gb28181=on --srt=on --rtsp=on --apm=on --utest=on --sanitizer=on --ffmpeg-opus=off --build-cache=on
RUN make utest ${MAKEARGS}

# Build benchmark tool.
RUN cd 3rdparty/srs-bench && make ${MAKEARGS}

