########################################################
FROM rockylinux:9 AS rocky9-baseline
COPY . /srs
RUN dnf makecache -y \
 && dnf -y install dnf-plugins-core \
 && dnf config-manager --set-enabled crb \
 && dnf -y install epel-release \
 && dnf -y groupinstall "Development Tools" \
 && dnf install -y wget ca-certificates which automake autoconf cmake tcl nasm yasm perl unzip patch xz xz-devel zlib-devel pkgconf-pkg-config libasan \
 && update-ca-trust && dnf clean all
RUN cd /srs/trunk && LIBS="-lz -llzma" ./configure --sanitizer=on --srt=off --gb28181=off && make

FROM rockylinux:9 AS rocky9-no-webrtc
COPY . /srs
RUN dnf makecache -y \
 && dnf -y install dnf-plugins-core \
 && dnf config-manager --set-enabled crb \
 && dnf -y install epel-release \
 && dnf -y groupinstall "Development Tools" \
 && dnf install -y wget ca-certificates which automake autoconf cmake tcl nasm yasm perl unzip patch xz xz-devel zlib-devel libasan \
 && update-ca-trust && dnf clean all
RUN cd /srs/trunk && LIBS="-lz -llzma" ./configure --sanitizer=on --srt=off --gb28181=off --rtc=off && make

FROM rockylinux:9 AS rocky9-no-asm
COPY . /srs
RUN dnf makecache -y \
 && dnf -y install dnf-plugins-core \
 && dnf config-manager --set-enabled crb \
 && dnf -y install epel-release \
 && dnf -y groupinstall "Development Tools" \
 && dnf install -y wget ca-certificates which automake autoconf cmake tcl nasm yasm perl unzip patch xz xz-devel zlib-devel libasan \
 && update-ca-trust && dnf clean all
RUN cd /srs/trunk && LIBS="-lz -llzma" ./configure --sanitizer=on --srt=off --gb28181=off --nasm=off --srtp-nasm=off && make

FROM rockylinux:9 AS rocky9-all
COPY . /srs
RUN dnf makecache -y \
 && dnf -y install dnf-plugins-core \
 && dnf config-manager --set-enabled crb \
 && dnf -y install epel-release \
 && dnf -y groupinstall "Development Tools" \
 && dnf install -y wget ca-certificates which automake autoconf cmake tcl nasm yasm perl unzip patch xz xz-devel zlib-devel libasan \
 && update-ca-trust && dnf clean all
RUN cd /srs/trunk && LIBS="-lz -llzma" ./configure --sanitizer=on --srt=on --gb28181=on --apm=on --h265=on && make

FROM rockylinux:9 AS rocky9-ansi-no-ffmpeg
COPY . /srs
RUN dnf makecache -y \
 && dnf -y install dnf-plugins-core \
 && dnf config-manager --set-enabled crb \
 && dnf -y install epel-release \
 && dnf -y groupinstall "Development Tools" \
 && dnf install -y wget ca-certificates which automake autoconf cmake tcl nasm yasm perl unzip patch xz xz-devel zlib-devel libasan \
 && update-ca-trust && dnf clean all
RUN cd /srs/trunk && LIBS="-lz -llzma" ./configure --sanitizer=on --srt=off --gb28181=off --cxx11=off --cxx14=off && make

########################################################

########################################################
FROM ubuntu:20.04 AS ubuntu20-baseline
COPY . /srs
RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    wget ca-certificates build-essential pkg-config git automake autoconf libtool cmake nasm yasm perl unzip xz-utils patch tclsh \
 && rm -rf /var/lib/apt/lists/*
RUN cd /srs/trunk && ./configure --sanitizer=on --srt=off --gb28181=off && make

FROM ubuntu:20.04 AS ubuntu20-all
COPY . /srs
RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    wget ca-certificates build-essential pkg-config git automake autoconf libtool cmake nasm yasm perl unzip xz-utils patch tclsh \
 && rm -rf /var/lib/apt/lists/*
RUN cd /srs/trunk && ./configure --sanitizer=on --srt=on --gb28181=on --apm=on --h265=on && make

########################################################
FROM ubuntu:22.04 AS ubuntu22-baseline
COPY . /srs
RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    wget ca-certificates build-essential pkg-config git automake autoconf libtool cmake nasm yasm perl unzip xz-utils patch tclsh \
 && rm -rf /var/lib/apt/lists/*
RUN cd /srs/trunk && ./configure --sanitizer=on --srt=off --gb28181=off && make

FROM ubuntu:22.04 AS ubuntu22-all
COPY . /srs
RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    wget ca-certificates build-essential pkg-config git automake autoconf libtool cmake nasm yasm perl unzip xz-utils patch tclsh \
 && rm -rf /var/lib/apt/lists/*
RUN cd /srs/trunk && ./configure --sanitizer=on --srt=on --gb28181=on && make

########################################################
FROM ubuntu:24.04 AS ubuntu24-baseline
COPY . /srs
RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    wget ca-certificates build-essential pkg-config git automake autoconf libtool cmake nasm yasm perl unzip xz-utils patch tclsh \
 && rm -rf /var/lib/apt/lists/*
RUN cd /srs/trunk && ./configure --sanitizer=on --srt=off --gb28181=off && make

FROM ubuntu:24.04 AS ubuntu24-all
COPY . /srs
RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    wget ca-certificates build-essential pkg-config git automake autoconf libtool cmake nasm yasm perl unzip xz-utils patch tclsh \
 && rm -rf /var/lib/apt/lists/*
RUN cd /srs/trunk && ./configure --sanitizer=on --srt=on --gb28181=on && make

FROM ubuntu:20.04 AS ubuntu20-cache-cross-armv7
COPY . /srs
RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    wget ca-certificates build-essential pkg-config git automake autoconf libtool cmake nasm yasm perl unzip xz-utils patch tclsh \
    gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf \
 && rm -rf /var/lib/apt/lists/*
RUN cd /srs/trunk && ./configure --sanitizer=on --cross-build --cross-prefix=arm-linux-gnueabihf- --ffmpeg-opus=on && make

FROM ubuntu:20.04 AS ubuntu20-cache-cross-aarch64
COPY . /srs
RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    wget ca-certificates build-essential pkg-config git automake autoconf libtool cmake nasm yasm perl unzip xz-utils patch tclsh \
    gcc-aarch64-linux-gnu g++-aarch64-linux-gnu \
 && rm -rf /var/lib/apt/lists/*
RUN cd /srs/trunk && ./configure --sanitizer=on --cross-build --cross-prefix=aarch64-linux-gnu- --ffmpeg-opus=on && make

########################################################
FROM ubuntu:22.04 AS ubuntu22-cache-cross-armv7
COPY . /srs
RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    wget ca-certificates build-essential pkg-config git automake autoconf libtool cmake nasm yasm perl unzip xz-utils patch tclsh \
    gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf \
 && rm -rf /var/lib/apt/lists/*
RUN cd /srs/trunk && ./configure --sanitizer=on --cross-build --cross-prefix=arm-linux-gnueabihf- --ffmpeg-opus=on && make

FROM ubuntu:22.04 AS ubuntu22-cache-cross-aarch64
COPY . /srs
RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    wget ca-certificates build-essential pkg-config git automake autoconf libtool cmake nasm yasm perl unzip xz-utils patch tclsh \
    gcc-aarch64-linux-gnu g++-aarch64-linux-gnu \
 && rm -rf /var/lib/apt/lists/*
RUN cd /srs/trunk && ./configure --sanitizer=on --cross-build --cross-prefix=aarch64-linux-gnu- --ffmpeg-opus=on && make

########################################################
FROM --platform=$TARGETPLATFORM ubuntu:24.04 AS ubuntu24-cache-cross-armv7
COPY . /srs
RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    wget ca-certificates build-essential pkg-config git automake autoconf libtool cmake nasm yasm perl unzip xz-utils patch tclsh \
    libopus-dev libssl-dev \
 && rm -rf /var/lib/apt/lists/*
RUN cd /srs/trunk && ./configure --sanitizer=on --ffmpeg-opus=on --sys-ssl=on && make

FROM --platform=$TARGETPLATFORM ubuntu:24.04 AS ubuntu24-cache-cross-aarch64
COPY . /srs
RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    wget ca-certificates build-essential pkg-config git automake autoconf libtool cmake nasm yasm perl unzip xz-utils patch tclsh \
    libopus-dev libssl-dev \
 && rm -rf /var/lib/apt/lists/*
RUN cd /srs/trunk && ./configure --sanitizer=on --ffmpeg-opus=on --sys-ssl=on && make
