FROM ubuntu:24.04

ARG MAKEARGS
RUN echo "MAKEARGS: ${MAKEARGS}"

ENV DEBIAN_FRONTEND=noninteractive

# Build and coverage dependencies
RUN apt-get update \
 && apt-get install -y --no-install-recommends \
    gcc g++ make patch unzip perl git ca-certificates \
    automake autoconf libtool cmake pkg-config nasm yasm xz-utils tclsh \
    zlib1g-dev liblzma-dev \
    libasan8 \
 && rm -rf /var/lib/apt/lists/*

# Build and install SRS.
COPY . /srs
WORKDIR /srs/trunk

# Note that we must enable the gcc7 or link failed.
# Enable sanitizer explicitly for coverage testing to catch memory issues.
RUN ./configure --rtsp=on --srt=on --gb28181=on --apm=on --h265=on --utest=on --gcov=on --sanitizer=on
RUN make utest ${MAKEARGS}

