FROM rockylinux:9

# version=4.0.145
ARG version
ARG SRS_AUTO_PACKAGER

# Install depends tools.
RUN dnf -y makecache \
 && dnf -y install zip \
 && dnf clean all

# Build and install SRS.
ADD srs-server-${version}.tar.gz /srs
WORKDIR /srs/srs-server-${version}/trunk
RUN ./scripts/package.sh --x86-x64 --gb28181=on --apm=on --h265=on --tag=${version}

