# docker config for srs.
# @see full.conf for detail config.

max_connections     1000;
# For docker, please use docker logs to manage the logs of SRS.
# See https://docs.docker.com/config/containers/logging/
srs_log_tank        console;
daemon              off;
rtmp {
    listen              1935;
}
http_api {
    enabled         on;
    listen          1985;
}
http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
}
rtc_server {
    enabled on;
    listen 8000;
    # @see https://ossrs.io/lts/en-us/docs/v7/doc/webrtc#config-candidate
    candidate $CANDIDATE;
}
vhost __defaultVhost__ {
    hls {
        enabled         on;
    }
    http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
    }
    rtc {
        enabled     on;
        # @see https://ossrs.io/lts/en-us/docs/v7/doc/webrtc#rtmp-to-rtc
        rtmp_to_rtc on;
        # @see https://ossrs.io/lts/en-us/docs/v7/doc/webrtc#rtc-to-rtmp
        rtc_to_rtmp on;
    }
    # Use OBS to publish to app 'live_src', we transcode with NVENC and publish to 'live' without suffix.
    transcode live_src {
        enabled on;
        ffmpeg /usr/local/srs/objs/ffmpeg/bin/ffmpeg;

        engine gpu_main {
            enabled on;
            vcodec h264_nvenc;
            vprofile high;
            vpreset p4;
            vparams -hwaccel cuda -hwaccel_output_format cuda;
            vfps 30;
            vwidth 1280;
            vheight 720;

            acodec aac;
            abitrate 128;
            asample_rate 44100;
            achannels 2;

            oformat flv;
            output rtmp://127.0.0.1:[port]/live/[stream]?vhost=[vhost];
        }
    }
}
